---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rend2973/public_html/ppg
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp license.txt $DEPLOYPATH
    - /bin/cp readme.html $DEPLOYPATH
    - /bin/cp wp-activate.php $DEPLOYPATH
    - /bin/cp wp-blog-header.php $DEPLOYPATH
    - /bin/cp wp-comments-post.php $DEPLOYPATH
    - /bin/cp wp-config.php $DEPLOYPATH
    - /bin/cp wp-config-sample.php $DEPLOYPATH
    - /bin/cp wp-cron.php $DEPLOYPATH
    - /bin/cp wp-links-opml.php $DEPLOYPATH
    - /bin/cp wp-load.php $DEPLOYPATH
    - /bin/cp wp-login.php $DEPLOYPATH
    - /bin/cp wp-mail.php $DEPLOYPATH
    - /bin/cp wp-settings.php $DEPLOYPATH
    - /bin/cp wp-signup.php $DEPLOYPATH
    - /bin/cp wp-trackback.php $DEPLOYPATH
    - /bin/cp xmlrpc.php $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp wp-admin $DEPLOYPATH
    - /bin/cp wp-content $DEPLOYPATH
    - /bin/cp wp-includes $DEPLOYPATH
